"""initial schema

Revision ID: 582ab3ef1b84
Revises: 
Create Date: 2026-05-12 09:59:55.285152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582ab3ef1b84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=120), nullable=False),
    sa.Column('schedule', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('source_path', sa.String(length=255), nullable=True),
    sa.Column('target_table', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('target_table', sa.String(length=120), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_logs')
    op.drop_table('etl_jobs')
    # ### end Alembic commands ###
